### ISSUE TITLE
Autour des projets de recherche

### ISSUE THREAD

**Issue by flavienalonzo** [infiniityr/portfolio-flavien#10]
Comment on fait déjà pour mettre du latex comme ça au milieu d'une phrase. Par exemple, j'ai une fonction $f:R\toR$.

Si c'est possible, ça pourrait être bien que tous les projets ne soient présentés que sur une ligne avec une barre de défilement horizontale pour parcourir la liste.

Est-ce qu'on peut automatiser la présentation du projet, genre position du bouton, taille de l'illustration, taille limite du titre ?

**Comment by infiniityr** [comment]
De ce que je vois dans ce qui a déjà été fait, il faut juste que le latex soit entre `$`.
Si ça ne fonctionne pas, je regarderai.

Je pense que c'est possible pour l'affichage des projets. Je vais essayer d'améliorer l'affichage du bloc également (bouton "En savoir plus" toujours à la même hauteur par exemple)

**Comment by infiniityr** [comment]
Il y a encore la partie Latex à faire

**Comment by infiniityr** [comment]
Trouvé pour le Latex, il faut écrire ton code de cette manière : 
```html
<p>Ton texte avec ta \(f_{u_{T}}\) dedans</p>
```
Du coup ce n'est pas les `$` qu'il faut utilisé mais `\(` et `\)`
