### ISSUE TITLE
Changer le symbole Sigma dans enseignement

### ISSUE THREAD

**Issue by flavienalonzo** [infiniityr/portfolio-flavien#4]
A côté de chaque truc dans enseignement il y a un symbole sigma. Je préférerai que le symbole sigma soit remplacer par le sigle TD, TP, project,etc... Le fait que ce soit orange, c'est joli.

**Comment by infiniityr** [comment]
C'est remplacé

J'ai supprimé le TD/TP/Projet entre parenthèse comme c'est écrit à cet endroit

Je suis pas super fan du "Projet" par contre... C'est mieux avec 2 caractères
