### ISSUE TITLE
Icone logo de truc connu

### ISSUE THREAD

**Issue by flavienalonzo** [infiniityr/portfolio-flavien#5]
Tout en haut et tout en bas de la page, il y a des liens vers d'autres sites web. Il s'agit de Research gate, orcid, linkedin et hal. Ces sites ont chacun leur logo et ils ne sont pas disponibles dans la liste des icones uil. Si c'est possible il faut mettre les logos associés

**Comment by flavienalonzo** [comment]
ça a changé les logos du haut mais pas ceux du bas -_-

**Comment by infiniityr** [comment]
Je ne savais pas qu'il y en avait en bas O:)
